### ISSUE TITLE
Add builds/CI

### ISSUE THREAD

**Issue by 4c0n** [SyliusCrafts/BootstrapTheme#60]
We need to test the theme against Sylius. It would be great to be able to run all the behat tests of Sylius.

https://github.com/Sylius/BootstrapTheme/issues/59

**Comment by jacquesbh** [comment]
May I suggest using Github Actions? :)

**Comment by oallain** [comment]
I think it's a very good idea, i can work on Github Actions if we decide to use it ;)

**Comment by pocky** [comment]
My only point about Github Actions vs TravisCI is simple: this should be a core decision for the sake of the core team (maintenance). If they want to switch to Github actions during the year, I will have no problem with Github actions. If they don't want to do this, we should stay on TravisCI (ping @pamil).

**Comment by Zales0123** [comment]
I would still like to see @pamil opinion, but IMO if you can improve something, then do it 😄 I see no reason to keep the Travis implementation if the one with Github Actions could be even a little bit better only because the other repositories use it… especially as the **BootstrapTheme** repository is kinda side project and is not so strictly related to the Sylius core as, for example, our official plugins 🖖

**Comment by 4c0n** [comment]
@oallain I see you started working on this. Did you talk to @pamil about this?

Also it would be great if the tests could be ran in the docker container setup and the CI would also have to build the container images for that. Push them to a registry and use them in subsequent steps. For that we would have to finish the other issue first. (https://github.com/Sylius/BootstrapTheme/issues/59)(https://github.com/Sylius/BootstrapTheme/pull/66)

Do you have some time to test the current status and provide some feedback?

**Comment by oallain** [comment]
Hello,

Yes, i started work on it to make a PoC :smile: 
It's work fine on my fork but Github Actions isn't executed (enable on https://github.com/Sylius/BootstrapTheme/settings/actions ?) in this repo. @pocky you can check it ?

No i haven't talk with Pamil, just with Mateusz :wink: 
I think too, use docket container can be great, but in next step, not on my first PR.

Sorry i haven't time to test docker container i next days :disappointed:

**Comment by 4c0n** [comment]
@oallain Ok well it's up to you. Personally I think a proof of concept is not really necessary as we know for a fact that it is possible to do this using github actions (it is what they're meant for). The challenge is not so much using github actions, but being able to run all the tests in the first place. If we use the containers locally and in the CI, we can prevent a lot of environment specific issues and don't have to go through the process of making the same thing work multiple times. It's also a lot easier to debug a failing test when you know you have the exact same environment running locally (or at least are capable of doing that).

From the messages above I kind of make up, that we're waiting on a more concise opinion from the core team, @Zales0123 Maybe you can discuss it and give us an answer? Your answer above seemed to be conditional on the opinion of @pamil.

@anthid was also working on running the Behat tests against the theme. Maybe you guys can team up?

**Comment by pocky** [comment]
Hello everybody,

First: Thank you all for your work on theses topics. I will have more time next week and will be available for tests tomorrow.

Sylius team is really busy and they don't have any time (for the moment), that's why I became maintainer of this repository. If the team can't give us an "official" answer and we can't wait (because of our projects), let's keep moving. Maybe we will take different directions but I am not worry about the long term: The journey is more important than the destination :smile:

**Comment by 4c0n** [comment]
Cool! You're right all work done on it is useful in one way or another. :smiley:

**Comment by anthid** [comment]
Hi,

@4c0n, I finally decided to go the tailwind route, so I have no plans to work again on Bootstrap theme, but I did a PR to sylius/sylius to enable theme testing ([11669](https://github.com/Sylius/Sylius/pull/11669)). Also while this PR is reviewed anyone can enable this feature in Sylius-Standard with this [gist](https://gist.github.com/anthid/dcc214804354c8d81013453d83aa219f).
